version: 2
updates:
- package-ecosystem: docker
  directory: /ubuntu-18.04
  ignore:
  - dependency-name: pizzafactory0contorno/piatto
    versions:
    - "!= 18.04-ubuntu"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-20.04
  ignore:
  - dependency-name: pizzafactory0contorno/piatto
    versions:
    - "!= 20.04-ubuntu"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-22.04
  ignore:
  - dependency-name: pizzafactory0contorno/piatto
    versions:
    - "!= 22.04-ubuntu"
  schedule:
    interval: daily
