name: build-container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bazelisk_version:
          - "1.17.0" 
        tag:
          - "18.04"
          - "20.04"
          - "22.04"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pizzafactory0contorno/bazel
          tags: |
            ${{ matrix.bazelisk_version }}-ubuntu${{ matrix.tag }}
            ${{ matrix.bazelisk_version }}-ubuntu${{ matrix.tag }}-{{sha}}
            ubuntu-${{ matrix.tag }}
            ubuntu-${{ matrix.tag }}-{{sha}}

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          file: ubuntu-${{ matrix.tag }}/Dockerfile.debian
          build-args: BAZELISK_VERSION=${{ matrix.bazelisk_version }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
