name: build-container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  results:
    # This job was inspired by https://github.com/orgs/community/discussions/26822#discussioncomment-5122101
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs: [docker]
    steps:
      - run: exit 1
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}

  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bazelisk_version:
          - "1.17.0" 
        tag:
          - "18.04"
          - "20.04"
          - "22.04"
    steps:
      - id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pizzafactory0contorno/${{ steps.repository.outputs.name }}
          tags: |
            ${{ matrix.bazelisk_version }}-ubuntu${{ matrix.tag }}
            ${{ matrix.bazelisk_version }}-ubuntu${{ matrix.tag }}-{{sha}}
            ubuntu-${{ matrix.tag }}
            ubuntu-${{ matrix.tag }}-{{sha}}

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: ubuntu-${{ matrix.tag }}/Dockerfile
          build-args: BAZELISK_VERSION=${{ matrix.bazelisk_version }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=${{ matrix.tag }}-${{ matrix.bazelisk_version }}
