name: build-container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: ubuntu-18.04
            dockerfile: Dockerfile.debian
            baseImage: ubuntu:18.04
            platforms: linux/amd64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platforms }}
          file: ${{ matrix.dockerfile }}
          build-args: BASE_IMAGE=${{ matrix.baseImage }}
          push: ${{ github.event_name == 'push' }}
          tags: pizzafactory0contorno/piatto:${{ matrix.tag }}
